package lpg2


/**
 * Low-Level type to act as recipient for error messages generated by a
 * parser/compiler.
 */
    /**
    * The following constants can be used as indexes to dereference
    * values in the msgLocation and errorLocation arrays.
    *
    * Locations are constructed by the method getLocation in LexStream which
    * takes two arguments  a start and an end location and returns an array
    * of 6 integers.
    */


const   OFFSET_INDEX int = 0
const   LENGTH_INDEX int = 1
const   START_LINE_INDEX int = 2
const   START_COLUMN_INDEX int = 3
const   END_LINE_INDEX int = 4
const   END_COLUMN_INDEX int = 5


type IMessageHandler interface {
    
/**
    *
    * When a location is nil, the value of its offset is 0.
    *
    * @param errorCode
    * @param msgLocation
    * @param errorLocation
    * @param filename
    * @param errorInfo
*/

    handleMessage(error_code int, msg_location []int, error_location []int,
                    filename  string, error_info []string)  
    
}